### PR TITLE
V2/analysis mongoose function

### LINKED ISSUE #5: v2/analysis-mongoose-function: Try feature of mongoose in save, find, update, delete, populate, etc and can wrap the idea of mongoose as knowledge that can provide for team to design architecture for restful api
- Mongoose have  just integrate create model schema.
- Not support crud as much -> need to deep down to understand how mongoose work with search, save, delete.
- Understand hook in mongoose

### PR DESCRIPTION
**Pull request by quangtudng**
Resolved #5 

I need people to review this new commit 304088b

* Updated validation logic for modules
* Improved validation logic for each route resolvers

### CODE REVIEW

**Comment by quangtudng** [comment]
New commit bce5341
* I have seperated the definition of schema so in the future we can declare a hook for some use cases. You can refer to the image below. The source for this document is : [https://mongoosejs.com/docs/middleware.html](url)
image

**Comment by dangphu2412** [comment]
Your code quality is good. Have you test some functionality of filter like:
This topic has mentioned some cases: [Mongoose query](https://stackoverflow.com/questions/36371190/mongoose-query-to-filter-an-array-and-populate-related-content)
I will merge this commit for now -> that others feature can use it for testing.

**Comment by dangphu2412** [comment]
- Validate function name is quite general. In the future, we may need a specific name related to a particular validation.
- And maybe permission schema is redundant, we may replace it with a tree module like category

**Comment by quangtudng** [comment]
> Your code quality is good. Have you test some functionality of filter like:
> This topic has mentioned some cases: [Mongoose query](https://stackoverflow.com/questions/36371190/mongoose-query-to-filter-an-array-and-populate-related-content)
> I will merge this commit for now -> that others feature can use it for testing.

I have done some testing with the filtering, although they were still simple use cases and may not cover all the use cases which we may encounter in the future. I will try to apply it into complex cases when i'm trying to build the rest builder

**Pull request merged**
